[project]
name = "cookbook"
version = "0.1.0"
dependencies = [
    "streamlit",
    "beautifulsoup4",
    "duckdb",
    "httpx>=0.28.1",
    "streamlit-extras>=0.7.8",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.4.1",
    "ruff>=0.12.1",
]
